steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/streamlit:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/streamlit:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
  - 'run'
  - 'deploy'
  - 'GCP-exam-dumps'
  - '--image'
  - 'gcr.io/$PROJECT_ID/streamlit:$COMMIT_SHA'
  - '--region'
  - 'asia-northeast3'
  - '--command'
  - 'streamlit'
  - '--args'
  - 'run'
  - '--args'
  - 'app.py'
  - '--port'
  - '8501'
images:
- 'gcr.io/$PROJECT_ID/streamlit:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
